### ISSUE TITLE
Re-organize columns in QC summary plus lineages output

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#107]
See example re-organized by louise and kristen which includes the heterozygosity metric
[template_format_QC_CDPH_210511_A00953_0299_BH7KLJDRXY.xlsx](https://github.com/ucsd-ccbb/covid_sequencing_analysis_pipeline/files/6672044/template_format_QC_CDPH_210511_A00953_0299_BH7KLJDRXY.xlsx)

**Comment by AmandaBirmingham** [comment]
@kmfisch I think the provided example can't really be what they want for production ... check out the far right edge of the spreadsheet, where they have an empty column (danger!) and then a new "ID" column, the pi metric, and then a bunch more nameless columns:

<img width="781" alt="Screen Shot 2021-06-22 at 4 27 36 PM" src="https://user-images.githubusercontent.com/10677935/123014248-a43f1300-d37a-11eb-8171-7fd67bc2789f.png">

Redoing the column order means nontrivial work redoing the tests, so I want to ensure that whoever is requesting this commits to the column order they want, no backsies ;)  Who is the stakeholder in charge of this?

**Comment by kmfisch** [comment]
Ooo good catch. Louise & Kristen created this so you can follow up with
them directly. If there are non-trivial changes we will want to have
stakeholder representative prioritize/authorize this as well.

**Comment by AmandaBirmingham** [comment]
@kmfisch in fact, the more I look at this, the more questions I have. The provided template includes a bunch of columns that aren't in the qc and lineages file because they come from the inspect metadata (e.g. excite_barcode) and drops a bunch of columns that are in the current qc and lineages file (e.g., seq_run).  Given this, we can give the stakeholders new file that has what they want in it (presuming we can get a clear read on what that is) but we will ALSO have to keep the existing qc and lineages file (under a different name if that would make them happier) because we cannot just throw out key columns that we may need later in the processing pipeline.

**Comment by kmfisch** [comment]
Ewww ok yes, definitely no dumping columns. Perhaps the stakeholder
representative should prioritize this now before we put additional effort
into it.

**Comment by rob-knight** [comment]
Revisit this once example of real output provided.

**Comment by AmandaBirmingham** [comment]
Closed to stakeholder satisfaction in release 3.1.0
