### ISSUE TITLE
Include in lineage calling on only samples in current sequencing run, not cumulative data

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#64]
From: "Laurent, Louise" 
Date: Thursday, March 18, 2021 at 11:21 AM
Subject: Re: Indel flag and Pangolin calls
 
Hi All,
A few adjustments to the below, based on Kristian's input on this morning's 10 am call -- pending Katie/Amanda checking with Karthik and Al that these fit what Bjorn does:
 
[snip]
 
4. [snip] Pangolin will only be run on samples in the current batch, not all of the previous batches.

**Comment by rob-knight** [comment]
I don't think this change should be made because 1. we are re-running the phylogenetic tree with all sequences, 2. lineages called with different versions of pangolin may mismatch the tree because of the version, not because of differences in the sequences. Also, Bjorn is independent of pangolin as far as we know, so the reference to "what Bjorn does" seems like it may be about something else.

**Comment by kmfisch** [comment]
@rob-knight and @AmandaBirmingham can we close this then?

**Comment by AmandaBirmingham** [comment]
Supplanted by #104
